Add the community section from the wireframe
ansible-community/community-website pull request #104
Opened 2023-09-05 10:21 UTC by oraNod

Fixes #80 

@leogallego @cybette I included the details from the issue here https://github.com/ansible-community/community-website/issues/80#issuecomment-1690494630

I think the mentioned "Devs & Contributors" content should go into the Contributor section of the homepage.

Also I put the meeting lists as a separate thing from the "social" icons. We could make it a single link to [the asking-questions-over-email section of the docs](https://docs.ansible.com/ansible/latest/community/communication.html?extIdCarryOver=true&sc_cid=701f2000001OH6uAAG#asking-questions-over-email)

However I felt like "Meeting Lists" doesn't really fit in the social category quite the same way. I thought I'd send the PR as is but can change it to an additional item on the row of icons. Thanks.

2023-09-05 11:55 UTC, maxamillion approved these changes
LGTM

2023-09-05 13:44 UTC, GregSutcliffe requested changes
Can we drop the mailing lists? It splits the audience with the forum and doesn't look as nice as the rest of the icons anyway. A link to the communication docs would be fine I think.

The icons are left-centred btw, which makes them look lopsided. But we can catch that in the style pass.

Otherwise LGTM

2023-09-05 14:30 UTC, cybette commented
+1 on excluding the mailing lists, the rest LGTM!

2023-09-06 08:29 UTC, GregSutcliffe reviewed
Icons are centred now, yay! Just a question about the CoC, looking good!

2023-09-06 10:48 UTC, oraNod commented on templates/homepage-community-band.tmpl
> +    <div class="community-conduct">
no, the button is too large but I was thinking we could get that in a styling round. I think it'd be fine to have the CoC in it's own band and that's a good suggestion.

2023-09-06 11:05 UTC, GregSutcliffe commented on templates/homepage-community-band.tmpl
> +    <div class="community-conduct">
Opened #107 for this, feel free to drop it from here.

2023-09-06 11:44 UTC, oraNod commented
@GregSutcliffe I've reworked the Code of Conduct part here and think it's better. I played around with it and it's not probably not worth creating a separate band just for that. A separate band will require yet another "Back to Top" link and maybe a new title and entry on the proposed tabbed navigation. I'd prefer to try and just keep the CoC discrete within the community section.

2023-09-06 11:45 UTC, oraNod commented on templates/homepage-community-band.tmpl
> +    <div class="community-conduct">
bah, I should have replied in this thread. https://github.com/ansible-community/community-website/pull/104#issuecomment-1708184339

my 2c is we make CoC more discrete but keep it in the community band.

2023-09-06 11:49 UTC, GregSutcliffe commented
Hmm, I'm still unconvinced, the flow on that feels weird - maybe I'm just used to seeing it at the end of the page though. Looking for other opinions here, reviewers!

2023-09-06 14:07 UTC, oraNod commented
@GregSutcliffe I think you're right. I like the idea of putting the code of conduct somewhere, maybe the footer like you said. But I'm sort of violating that "direct to the forum as much as possible" pattern we want to establish.

2023-09-06 15:26 UTC, GregSutcliffe commented
I *do* think it needs to be present, I'm just not entirely sure this is the place (or perhaps it's just the style). But let's not hold this up over the bikeshedding, and continue in #107

2023-09-06 15:29 UTC, merged